# Generated by Django 2.1.1 on 2018-09-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('health_type', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
