# Generated by Django 2.1.1 on 2018-09-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserColor',
        ),
    ]
