# Generated by Django 2.1.1 on 2018-09-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180916_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercolor',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercolor',
            name='user',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
